### ISSUE TITLE
Add support for Android 6.

### ISSUE THREAD

**Issue by mathwhiz1212** [scheich/SyncWifi#2]
Please add support for Android 6. This is a great app and I would like to use it on my new phone.

**Comment by scheich** [comment]
Can you describe, whats not working? Does the app force closes? If yes, can you provide a logcat?

**Comment by mathwhiz1212** [comment]
It says that it cannot find any accounts. I figured out that I have to manually go to Settings > Applications > Manage Applications > SyncWifi > Permissions > Enable contacts permission. After that it seems to work.
